# ### Site settings ###

# used in layouts and header
url: "http://conemu.github.io"

# used with breadcrumbs
site_name: "conemu.github.io"

# main mirror location
mirror: ""


# ### Build settings ###

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

# Allow redirections
gems:
  - jekyll-redirect-from


# ### Page defaults ###

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "root"
      title: "ConEmu - Windows terminal emulator"
      site_label: "Windows terminal"
      docfolder: /en
      pagelang: en
  -
    scope:
      path: "en"
      type: "pages"
    values:
      layout: "docs_en"
      title: "ConEmu - Documentation"
      site_label: "Windows terminal"
      docfolder: /en
      pagelang: en
  -
    scope:
      path: "en-w"
      type: "pages"
    values:
      layout: "docs_en"
      title: "ConEmu - Documentation"
      site_label: "Windows terminal"
      docfolder: /en-w
      pagelang: en
  -
    scope:
      path: "ru"
      type: "pages"
    values:
      layout: "docs_ru"
      title: "ConEmu - эмулятор терминала Windows"
      site_label: "терминал Windows"
      docfolder: /ru
      pagelang: ru
  -
    scope:
      path: "ru-w"
      type: "pages"
    values:
      layout: "docs_ru"
      title: "ConEmu - эмулятор терминала Windows"
      site_label: "терминал Windows"
      docfolder: /ru-w
      pagelang: ru
