# Site settings
title: ConEmu - Windows Console Emulator
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Official site of ConEmu.
  Handy Windows terminal with tabs, splits, fast access to favourite shells,
  automation and more.
# baseurl: "/"
url: "http://conemu.github.io"
twitter_username: ConEmuMaximus5
github_username:  Maximus5

# Build settings
# markdown: kramdown

# Allow redirections
gems:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "root"
      title: "ConEmu - Windows terminal emulator"
      docfolder: /en
  -
    scope:
      path: "en"
      type: "pages"
    values:
      layout: "docs_en"
      title: "ConEmu - Documentation"
      docfolder: /en
  -
    scope:
      path: "en-w"
      type: "pages"
    values:
      layout: "docs_en"
      title: "ConEmu - Documentation"
      docfolder: /en-w
  -
    scope:
      path: "ru"
      type: "pages"
    values:
      layout: "docs_ru"
      title: "ConEmu - эмулятор терминала Windows"
      docfolder: /ru
  -
    scope:
      path: "ru-w"
      type: "pages"
    values:
      layout: "docs_ru"
      title: "ConEmu - эмулятор терминала Windows"
      docfolder: /ru-w
